// <auto-generated />
using System;
using BandAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BandAPI.Migrations
{
    [DbContext(typeof(BandAlbumContext))]
    partial class BandAlbumContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BandAPI.Entities.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(400)")
                        .HasMaxLength(400);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("BandId");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1520ee8a-17ef-4ac7-9585-7f090e238cfb"),
                            BandId = new Guid("15b239b4-369f-49f0-a0b8-531abf22d64e"),
                            Description = "One of the best heavy metal albums ever.",
                            Title = "Master of Puppets"
                        },
                        new
                        {
                            Id = new Guid("9c4c3f62-5f42-4729-b08e-3dcefdc7f04c"),
                            BandId = new Guid("78727b66-4fc8-4e00-908f-af747f68bf68"),
                            Description = "Amazing Rock album with raw sound.",
                            Title = "Appetite for Destruction"
                        },
                        new
                        {
                            Id = new Guid("d284779e-c930-4011-b190-44b5e359a758"),
                            BandId = new Guid("deb0be4c-a2de-4465-8621-0d8dc0e61185"),
                            Description = "Very groovy album.",
                            Title = "Waterloo"
                        },
                        new
                        {
                            Id = new Guid("e80e2ef3-4e13-4dd6-a8b3-a6b1ccfa517c"),
                            BandId = new Guid("fadf9cf0-573b-4e34-b611-d7e50ee6f595"),
                            Description = "Arguably one of the best albums by Oasis.",
                            Title = "Be Here Now"
                        },
                        new
                        {
                            Id = new Guid("0cfda149-e1d3-4b22-9d24-5418d4945597"),
                            BandId = new Guid("af44229e-d4b9-4081-9294-6957798022a6"),
                            Description = "Awesome Debut album by A-ha.",
                            Title = "Hunting Hight and Low"
                        });
                });

            modelBuilder.Entity("BandAPI.Entities.Band", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Founded")
                        .HasColumnType("datetime2");

                    b.Property<string>("MainGenre")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Bands");

                    b.HasData(
                        new
                        {
                            Id = new Guid("15b239b4-369f-49f0-a0b8-531abf22d64e"),
                            Founded = new DateTime(1980, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MainGenre = "Heavy Metal",
                            Name = "Metallica"
                        },
                        new
                        {
                            Id = new Guid("78727b66-4fc8-4e00-908f-af747f68bf68"),
                            Founded = new DateTime(1985, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MainGenre = "Rock",
                            Name = "Guns n Roses"
                        },
                        new
                        {
                            Id = new Guid("deb0be4c-a2de-4465-8621-0d8dc0e61185"),
                            Founded = new DateTime(1965, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MainGenre = "Disco",
                            Name = "ABBA"
                        },
                        new
                        {
                            Id = new Guid("fadf9cf0-573b-4e34-b611-d7e50ee6f595"),
                            Founded = new DateTime(1991, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MainGenre = "Alternative",
                            Name = "Oasis"
                        },
                        new
                        {
                            Id = new Guid("af44229e-d4b9-4081-9294-6957798022a6"),
                            Founded = new DateTime(1981, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MainGenre = "Pop",
                            Name = "A-ha"
                        });
                });

            modelBuilder.Entity("BandAPI.Entities.Album", b =>
                {
                    b.HasOne("BandAPI.Entities.Band", "Band")
                        .WithMany("Albums")
                        .HasForeignKey("BandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
